# This section is to internal connections between pods usind ClusterIP service

apiVersion: v1
kind: Service
metadata:
  name: nexus
spec:
  selector:
    app: nexus
  ports:
  - port: 8081
    targetPort: 8081
    name: nexus-dashboard
  - port: 8085
    targetPort: 8085
    name: docker-repo

---
# This section is related to expose jenkins to port 30000 to be accessable externally
# using node service 

apiVersion: v1
kind: Service
metadata:
  name: nexus-node-service
spec:
  type: NodePort
  selector:
    app: nexus
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081



