apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
spec:
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3
        ports:
        - containerPort: 8081
        - containerPort: 8085
        volumeMounts:
          - name: nexus-pv
            mountPath: /nexus-data
      volumes:
      - name: nexus-pv
        persistentVolumeClaim:
          claimName: nexus-pvc
