version: 2.1
orbs:
  slack: circleci/slack@4.9.3
jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run:
          name: Check job status
          command: echo $CIRCLE_JOB_STATUS
      - slack/notify:
          event: ${{ success() ? 'pass' : 'fail' }}  # Set event based on job status
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": " ${{ success() ? ':white_check_mark: Success' : ':x: Failure' }}: $CIRCLE_USERNAME's build of \n<$CIRCLE_BUILD_URL|$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME>\n(<https://app.circleci.com/pipelines/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME?branch=$CIRCLE_BRANCH|$CIRCLE_BRANCH>) \n- <$CIRCLE_BUILD_URL|$CIRCLE_JOB> ${{ success() ? ':heavy_check_mark:' : ':heavy_multiplication_mark:' }}"
                  }
                }
              ]
            }  
workflows:
  send-notification:
    jobs:
      - notify:
          context: slack-secrets
