version: 2.1

# Configure Slack Notifications
orbs:
  slack: circleci/slack@4.12.0

commands:
  # Configure Slack

  notify_on_failure:
    steps:
      - slack/notify:
          event: fail
          channel: project
          template: basic_fail_1

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: exit 1
      - notify_on_failure
workflows:
  default:
    jobs:
      - print_hello
