version: 2.1
orbs:
  slack: circleci/slack@4.9.3
jobs:
  notify:
    docker:
      - image: "cimg/base:stable"
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Project:* $CIRCLE_PROJECT_REPONAME\n*Status:* $CIRCLE_JOB_STATUS\n*Person:* $CIRCLE_USERNAME\n*Commit Title:* $CIRCLE_COMMIT_SUBJECT"
                  },
                  "color": "${CIRCLE_JOB_STATUS == 'success' ? 'good' : 'danger'}"
                }
              ]
            }
          event: always
workflows:
  send-notification:
    jobs:
      - notify:
          context: slack-secrets
