version: 2.1
orbs:
  slack: circleci/slack@4.9.3
jobs:
  notify:
    docker:
      - image: "cimg/base:stable"
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Project: $CIRCLE_PROJECT_REPONAME\nStatus: $CIRCLE_JOB\nPerson: $CIRCLE_USERNAME\nCommit Title: $CIRCLE_COMMIT_SUBJECT"
                  }
                }
              ]
            }
          event: always
workflows:
  send-notification:
    jobs:
      - notify:
          context: slack-secrets
