version: 2.1

# Declare Slack orb for Slack integration
orbs:
  slack: circleci/slack@4.9.3

# Define the job to send notifications to Slack
jobs:
  notify:
    # Use a Docker image for the job environment
    docker:
      - image: "cimg/base:stable"
    steps:
      # Send a custom notification to Slack on failure
      - slack/notify:
          # Define the custom message using Slack Block Kit syntax
          event: fail
          custom: | 
            {
                "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "Failed: $CIRCLE_USERNAME's build of \n<$CIRCLE_BUILD_URL|$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME>\n(<https://app.circleci.com/pipelines/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME?branch=$CIRCLE_BRANCH|$CIRCLE_BRANCH>) \n- <$CIRCLE_BUILD_URL|$CIRCLE_JOB> failed" 
                        },
                        # Change the color of the message block to red for failure
                        "color": "danger"
                    }
                ]
            }
      # Send a greeting message to Slack on success
      - slack/notify:
          # Define the custom message using Slack Block Kit syntax
          event: pass
          custom: | 
            {
                "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "Congratulations! $CIRCLE_USERNAME's build of \n<$CIRCLE_BUILD_URL|$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME>\n(<https://app.circleci.com/pipelines/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME?branch=$CIRCLE_BRANCH|$CIRCLE_BRANCH>) \n- <$CIRCLE_BUILD_URL|$CIRCLE_JOB> succeeded" 
                        },
                        # Change the color of the message block to green for success
                        "color": "good"
                    }
                ]
            }

# Define the workflow to trigger the notification job
workflows:
  send-notification:
    jobs:
      # Trigger the notify job to send the Slack notification
      - notify:
          # Specify the context containing Slack secrets
          context: slack-secrets
