version: 2.1
orbs:
  slack: circleci/slack@4.9.3
jobs:
  hello_world:
    docker:
      - image: "cimg/base:stable"
    steps:
      - run:
          name: Hello World
          command: exit 1  # This command will always fail

  notify_on_failure:
    docker:
      - image: "cimg/base:stable"
    steps:
      - slack/notify:
          event: fail
          custom: |
            {
              "text": "CircleCI job failed.",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Job Failed. :red_circle:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Job*: ${CIRCLE_JOB}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project*: $CIRCLE_PROJECT_REPONAME"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*: $CIRCLE_BRANCH"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author*: $CIRCLE_USERNAME"
                    }
                  ],
                  "accessory": {
                    "type": "image",
                    "image_url": "https://production-cci-com.imgix.net/blog/media/circle-logo-badge-black.png",
                    "alt_text": "CircleCI logo"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Mentions*: $SLACK_PARAM_MENTIONS"
                    }
                  ]
                }
              ]
            }

workflows:
  version: 2
  build_and_notify:
    jobs:
      - hello_world
      - notify_on_failure:
          requires:
            - hello_world
